[tool.poetry]
name = "quiz"
version = "0.1.0"
description = ""
authors = ["Mikita <nszmygalow@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
termcolor = "^2.4.0"
pytest = "^8.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
